/**
 * A curated emoji set with search keywords.
 *
 * Not a dependency: the brief's rule is to build with what we have rather than
 * invent a new one, and every emoji library ships either a megabyte of data or
 * a runtime that fetches it. This is the subset a work tool actually reaches
 * for — objects, status, people, places, symbols — with the keywords people
 * type rather than the Unicode names nobody knows.
 */
export type EmojiGroup = { name: string; emoji: { c: string; n: string }[] };

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    name: "Work",
    emoji: [
      { c: "🚀", n: "rocket launch ship release" },
      { c: "🛰️", n: "satellite platform infra space" },
      { c: "🧩", n: "puzzle piece integration module" },
      { c: "📦", n: "package box release build" },
      { c: "🔭", n: "telescope discovery research" },
      { c: "⚙️", n: "gear settings config engine" },
      { c: "🎯", n: "target goal okr aim" },
      { c: "🌱", n: "seedling growth new" },
      { c: "🛟", n: "lifebuoy support helpdesk rescue" },
      { c: "📊", n: "bar chart analytics data report" },
      { c: "📈", n: "chart up growth trending" },
      { c: "📉", n: "chart down decline" },
      { c: "🎨", n: "palette design art brand" },
      { c: "🔐", n: "lock security auth private" },
      { c: "🔑", n: "key access credential" },
      { c: "🧾", n: "receipt billing invoice finance" },
      { c: "💳", n: "card payment billing" },
      { c: "🏗️", n: "construction building platform" },
      { c: "🧪", n: "test tube qa experiment lab" },
      { c: "🔬", n: "microscope research analysis" },
      { c: "🛠️", n: "tools ops maintenance fix" },
      { c: "🔧", n: "wrench fix tooling" },
      { c: "🪛", n: "screwdriver fix tweak" },
      { c: "🧰", n: "toolbox kit utilities" },
      { c: "📐", n: "ruler design spec measure" },
      { c: "🗂️", n: "dividers files organise index" },
      { c: "📁", n: "folder files project" },
      { c: "📋", n: "clipboard tasks checklist" },
      { c: "📝", n: "memo notes write doc" },
      { c: "📄", n: "page document file" },
      { c: "📌", n: "pin pinned important" },
      { c: "📎", n: "paperclip attachment" },
      { c: "🗓️", n: "calendar schedule sprint" },
      { c: "⏱️", n: "stopwatch performance latency timing" },
      { c: "⏳", n: "hourglass waiting pending slow" },
      { c: "🔔", n: "bell notification alert" },
      { c: "🏷️", n: "label tag category" },
      { c: "🧭", n: "compass direction roadmap strategy" },
      { c: "🗺️", n: "map roadmap plan" },
      { c: "🏁", n: "flag finish done complete milestone" },
      { c: "🎛️", n: "control knobs dashboard data" },
      { c: "🖥️", n: "desktop computer machine" },
      { c: "📱", n: "phone mobile ios android" },
      { c: "⌨️", n: "keyboard input typing" },
      { c: "🖱️", n: "mouse pointer click" },
      { c: "💾", n: "floppy save storage disk" },
      { c: "🗄️", n: "cabinet database archive storage" },
      { c: "☁️", n: "cloud hosting infra" },
      { c: "🌐", n: "globe web network internet" },
      { c: "🔌", n: "plug integration connect api" },
      { c: "🧱", n: "brick wall foundation block" },
      { c: "⚡", n: "zap fast performance speed" },
      { c: "🔥", n: "fire hot urgent incident" },
      { c: "💡", n: "bulb idea proposal insight" },
      { c: "🧠", n: "brain thinking ai ml smart" },
      { c: "🤖", n: "robot bot automation ai" },
      { c: "👾", n: "alien monster bug game" },
      { c: "🐛", n: "bug defect issue" },
      { c: "🕷️", n: "spider crawler scraper" },
      { c: "🔍", n: "search magnify find query" },
      { c: "🧹", n: "broom cleanup chore tidy" },
      { c: "♻️", n: "recycle refactor reuse" },
      { c: "🧊", n: "ice frozen cold backlog" },
      { c: "🪄", n: "wand magic auto generate" },
    ],
  },
  {
    name: "Status",
    emoji: [
      { c: "✅", n: "check done complete tick pass" },
      { c: "☑️", n: "checkbox done ticked" },
      { c: "❌", n: "cross fail no error" },
      { c: "⛔", n: "no entry blocked stop" },
      { c: "🚫", n: "prohibited blocked forbidden" },
      { c: "⚠️", n: "warning caution risk" },
      { c: "🛑", n: "stop halt blocker" },
      { c: "🟢", n: "green circle healthy good ok" },
      { c: "🟡", n: "yellow circle warning degraded" },
      { c: "🔴", n: "red circle down critical" },
      { c: "🔵", n: "blue circle info" },
      { c: "🟣", n: "purple circle" },
      { c: "🟠", n: "orange circle" },
      { c: "⚪", n: "white circle neutral empty" },
      { c: "⚫", n: "black circle off" },
      { c: "🔺", n: "red triangle up high increase" },
      { c: "🔻", n: "red triangle down low decrease" },
      { c: "⭐", n: "star favourite starred important" },
      { c: "🌟", n: "glowing star highlight special" },
      { c: "❗", n: "exclamation important urgent" },
      { c: "❓", n: "question unknown unclear" },
      { c: "💯", n: "hundred perfect complete" },
      { c: "🆕", n: "new badge" },
      { c: "🆗", n: "ok approved" },
      { c: "🔁", n: "repeat recurring loop retry" },
      { c: "⏸️", n: "pause on hold paused" },
      { c: "▶️", n: "play start resume go" },
      { c: "⏭️", n: "next skip forward" },
    ],
  },
  {
    name: "People",
    emoji: [
      { c: "👋", n: "wave hello hi greeting" },
      { c: "👍", n: "thumbs up approve lgtm yes" },
      { c: "👎", n: "thumbs down reject no" },
      { c: "👏", n: "clap applause well done" },
      { c: "🙏", n: "pray thanks please" },
      { c: "🤝", n: "handshake deal agreement partner" },
      { c: "💪", n: "muscle strong effort" },
      { c: "🫡", n: "salute acknowledged on it" },
      { c: "🤔", n: "thinking hmm consider" },
      { c: "🙃", n: "upside down irony" },
      { c: "😅", n: "sweat smile nervous close" },
      { c: "😬", n: "grimace awkward yikes" },
      { c: "🤯", n: "mind blown shocked" },
      { c: "🥳", n: "party celebrate launch" },
      { c: "😴", n: "sleeping idle stale dormant" },
      { c: "🧑‍💻", n: "developer engineer coder" },
      { c: "🧑‍🎨", n: "designer artist" },
      { c: "🧑‍🔬", n: "scientist researcher qa" },
      { c: "🧑‍🏫", n: "teacher docs training" },
      { c: "🕵️", n: "detective investigate debug" },
      { c: "👀", n: "eyes looking review watching" },
      { c: "🦸", n: "hero superhero saved" },
      { c: "👥", n: "people team group" },
      { c: "🗣️", n: "speaking voice feedback" },
      { c: "💬", n: "speech comment chat discussion" },
      { c: "📣", n: "megaphone announce launch" },
    ],
  },
  {
    name: "Objects",
    emoji: [
      { c: "🏆", n: "trophy win award goal" },
      { c: "🎁", n: "gift present bonus" },
      { c: "🎉", n: "party popper celebrate ship" },
      { c: "🎊", n: "confetti celebrate" },
      { c: "🔗", n: "link url chain reference" },
      { c: "🪝", n: "hook webhook" },
      { c: "🧲", n: "magnet attract pull" },
      { c: "🔦", n: "torch flashlight investigate" },
      { c: "🕯️", n: "candle vigil quiet" },
      { c: "📡", n: "antenna signal telemetry" },
      { c: "🛎️", n: "bell service desk request" },
      { c: "🧯", n: "extinguisher incident firefight" },
      { c: "🚨", n: "siren alert incident emergency" },
      { c: "🔒", n: "locked private secure" },
      { c: "🔓", n: "unlocked open public" },
      { c: "🛡️", n: "shield protection security defence" },
      { c: "⚖️", n: "scales balance tradeoff legal" },
      { c: "💎", n: "gem premium quality valuable" },
      { c: "🪙", n: "coin cost price money" },
      { c: "💰", n: "money bag budget revenue" },
      { c: "🧮", n: "abacus calculate count" },
      { c: "📬", n: "mailbox inbox mail" },
      { c: "✉️", n: "envelope email message" },
      { c: "📮", n: "postbox send submit" },
      { c: "🖼️", n: "picture image media asset" },
      { c: "🎬", n: "clapper video film recording" },
      { c: "🎧", n: "headphones audio listen" },
      { c: "🎙️", n: "microphone record call" },
      { c: "📞", n: "phone call dial" },
      { c: "📹", n: "video camera record meeting" },
    ],
  },
  {
    name: "Places & nature",
    emoji: [
      { c: "🌍", n: "earth globe world region" },
      { c: "🌎", n: "americas globe region" },
      { c: "🌏", n: "asia globe region" },
      { c: "🏠", n: "house home local" },
      { c: "🏢", n: "office building company" },
      { c: "🏭", n: "factory production pipeline" },
      { c: "🏥", n: "hospital health triage" },
      { c: "🏦", n: "bank finance" },
      { c: "🌉", n: "bridge migration connect" },
      { c: "🛣️", n: "motorway road roadmap path" },
      { c: "🚦", n: "traffic light gating status" },
      { c: "🌊", n: "wave flow stream" },
      { c: "🌋", n: "volcano eruption incident" },
      { c: "🏔️", n: "mountain peak challenge" },
      { c: "🌲", n: "tree evergreen forest" },
      { c: "🍃", n: "leaf light green eco" },
      { c: "🌙", n: "moon night dark" },
      { c: "☀️", n: "sun day light bright" },
      { c: "🌈", n: "rainbow variety spectrum" },
      { c: "❄️", n: "snowflake freeze frozen cold" },
      { c: "🔮", n: "crystal ball forecast predict" },
    ],
  },
  {
    name: "Animals",
    emoji: [
      { c: "🐙", n: "octopus many arms parallel" },
      { c: "🐧", n: "penguin linux" },
      { c: "🦊", n: "fox firefox clever" },
      { c: "🐳", n: "whale docker container" },
      { c: "🐬", n: "dolphin smart fast" },
      { c: "🦉", n: "owl wise night" },
      { c: "🐝", n: "bee busy swarm" },
      { c: "🦋", n: "butterfly transform change" },
      { c: "🐢", n: "turtle slow performance" },
      { c: "🐇", n: "rabbit fast quick" },
      { c: "🦀", n: "crab rust" },
      { c: "🐍", n: "snake python" },
      { c: "🐘", n: "elephant postgres memory" },
      { c: "🦓", n: "zebra stripes" },
      { c: "🦁", n: "lion brave lead" },
      { c: "🐻", n: "bear" },
      { c: "🐼", n: "panda" },
      { c: "🦅", n: "eagle watch high" },
    ],
  },
  {
    name: "Food",
    emoji: [
      { c: "☕", n: "coffee morning standup break" },
      { c: "🍵", n: "tea calm break" },
      { c: "🍕", n: "pizza food team lunch" },
      { c: "🍰", n: "cake birthday celebrate" },
      { c: "🍪", n: "cookie snack cache" },
      { c: "🍿", n: "popcorn watching drama" },
      { c: "🥕", n: "carrot incentive" },
      { c: "🌶️", n: "chilli spicy hot take" },
      { c: "🧂", n: "salt seasoning salty" },
      { c: "🍋", n: "lemon sour" },
      { c: "🍌", n: "banana" },
      { c: "🍓", n: "strawberry" },
      { c: "🥑", n: "avocado" },
      { c: "🧁", n: "cupcake treat" },
    ],
  },
  {
    name: "Symbols",
    emoji: [
      { c: "♻️", n: "recycle reuse refactor" },
      { c: "⚛️", n: "atom react physics" },
      { c: "♾️", n: "infinity endless unlimited" },
      { c: "➕", n: "plus add create new" },
      { c: "➖", n: "minus remove subtract" },
      { c: "✳️", n: "asterisk required note" },
      { c: "✴️", n: "sparkle special" },
      { c: "〽️", n: "part alternation" },
      { c: "🔤", n: "letters text abc" },
      { c: "🔢", n: "numbers count digits" },
      { c: "#️⃣", n: "hash channel tag number" },
      { c: "🔣", n: "symbols" },
      { c: "🆔", n: "id identifier" },
      { c: "🔄", n: "sync refresh reload cycle" },
      { c: "⏰", n: "alarm clock due deadline" },
      { c: "🕐", n: "clock time schedule" },
      { c: "💤", n: "zzz idle asleep stale" },
      { c: "✨", n: "sparkles new feature polish magic" },
      { c: "💫", n: "dizzy shine" },
      { c: "🌀", n: "cyclone spiral loop" },
    ],
  },
];

export const ALL_EMOJI = EMOJI_GROUPS.flatMap((group) =>
  group.emoji.map((entry) => ({ ...entry, group: group.name })),
);

export function searchEmoji(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return null;
  return ALL_EMOJI.filter(
    (entry) => entry.n.includes(q) || entry.c === q,
  );
}
